batch_type: numel
batch_bins: 200000
accum_grad: 1
max_epoch: 15
patience: none
init: none
best_model_criterion:
-   - valid
    - cer_ctc
    - min
keep_nbest_models: 1

encoder: transformer
encoder_conf:
    input_layer: conv2d2
    num_blocks: 1
    linear_units: 2048
    dropout_rate: 0.2
    output_size: 256  # dimension of attention
    attention_heads: 8
    attention_dropout_rate: 0.2

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.0
    length_normalized_loss: false
    extract_feats_in_collect_stats: false   # Note: "False" means during collect stats (stage 10), generating dummy stats files rather than extract_feats by forward frontend.

optim: adamw
optim_conf:
    lr: 0.0001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 300

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_url  # Note: If the upstream is changed, please change the input_size in the preencoder.
        upstream_ckpt: https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr2_300m.pt
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80
